import {defineConfig} from 'vite';
import laravel from 'laravel-vite-plugin';
import fs from 'fs';
import path from 'path';

const publicDisplayScripts = [
    'shalat-schedule.js',
    'iqamah-shalat-modal.js',
    'kiosk-mode.js',
    'modal-state.js',
    'next-shalat-counter.js',
    'time-calculator.js',
];

const appOwnedPluginScripts = [
    'matrix-display.js',
    'number-format.js',
    'short-currency.js',
];

const vendorPluginScripts = [
    'jquery.datetimepicker.js',
    'noty.js',
    'select2.min.js',
];

const vendorPluginStyles = [
    'jquery.datetimepicker.css',
    'select2-bootstrap.min.css',
    'select2.min.css',
];

function createGeneratedFileHeader(source, output) {
    if (path.extname(output) === '.css') {
        return [
            `/* Generated from ${source}.`,
            ' * Do not edit this file directly. Run `npm run build` after editing the source file.',
            ' */',
            '',
        ].join('\n');
    }

    return [
        `// Generated from ${source}.`,
        '// Do not edit this file directly. Run `npm run build` after editing the source file.',
        '',
    ].join('\n');
}

function writeGeneratedScript(source, output) {
    fs.mkdirSync(path.dirname(output), {recursive: true});
    fs.writeFileSync(output, createGeneratedFileHeader(source, output) + fs.readFileSync(source, 'utf8'));
}

/**
 * Copies the hand-maintained public display / plugin assets into `public/`
 * during the Vite build. This replaces the equivalent step that used to run
 * in Laravel Mix (`webpack.mix.js`).
 */
function copyStaticAssets() {
    return {
        name: 'buku-masjid-copy-static-assets',
        apply: 'build',
        closeBundle() {
            publicDisplayScripts.forEach((fileName) => writeGeneratedScript(
                `resources/assets/js/public_display/${fileName}`,
                `public/js/public_display/${fileName}`,
            ));

            appOwnedPluginScripts.forEach((fileName) => writeGeneratedScript(
                `resources/assets/js/plugins/${fileName}`,
                `public/js/plugins/${fileName}`,
            ));

            vendorPluginScripts.forEach((fileName) => writeGeneratedScript(
                `resources/vendor/js/${fileName}`,
                `public/js/plugins/${fileName}`,
            ));

            vendorPluginStyles.forEach((fileName) => writeGeneratedScript(
                `resources/vendor/css/${fileName}`,
                `public/css/plugins/${fileName}`,
            ));
        },
    };
}

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/js/app.js'],
        }),
        copyStaticAssets(),
    ],
    base: './',
});
