let mix = require('laravel-mix');
let fs = require('fs');
let path = require('path');

const publicDisplayScripts = [
    'shalat-schedule.js',
    'iqamah-shalat-modal.js',
    'kiosk-mode.js',
    'modal-state.js',
    'next-shalat-counter.js',
    'time-calculator.js',
];

const appOwnedPluginScripts = [
    'matrix-display.js',
    'number-format.js',
    'short-currency.js',
];

const vendorPluginScripts = [
    'jquery.datetimepicker.js',
    'noty.js',
    'select2.min.js',
];

const vendorPluginStyles = [
    'jquery.datetimepicker.css',
    'select2-bootstrap.min.css',
    'select2.min.css',
];

function createGeneratedFileHeader(source, output) {
    if (path.extname(output) === '.css') {
        return [
            `/* Generated from ${source}.`,
            ' * Do not edit this file directly. Run `npm run dev` after editing the source file.',
            ' */',
            '',
        ].join('\n');
    }

    return [
        `// Generated from ${source}.`,
        '// Do not edit this file directly. Run `npm run dev` after editing the source file.',
        '',
    ].join('\n');
}

function writeGeneratedScript(source, output) {
    fs.mkdirSync(path.dirname(output), { recursive: true });
    fs.writeFileSync(output, createGeneratedFileHeader(source, output) + fs.readFileSync(source, 'utf8'));
}

function writeGeneratedPublicDisplayScript(fileName) {
    writeGeneratedScript(
        `resources/assets/js/public_display/${fileName}`,
        `public/js/public_display/${fileName}`
    );
}

function writeGeneratedAppOwnedPluginScript(fileName) {
    writeGeneratedScript(
        `resources/assets/js/plugins/${fileName}`,
        `public/js/plugins/${fileName}`
    );
}

function writeGeneratedVendorPluginScript(fileName) {
    writeGeneratedScript(
        `resources/vendor/js/${fileName}`,
        `public/js/plugins/${fileName}`
    );
}

function writeGeneratedVendorPluginStyle(fileName) {
    writeGeneratedScript(
        `resources/vendor/css/${fileName}`,
        `public/css/plugins/${fileName}`
    );
}

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/assets/js/app.js', 'public/js')
    .then(() => {
        publicDisplayScripts.forEach(writeGeneratedPublicDisplayScript);
        appOwnedPluginScripts.forEach(writeGeneratedAppOwnedPluginScript);
        vendorPluginScripts.forEach(writeGeneratedVendorPluginScript);
        vendorPluginStyles.forEach(writeGeneratedVendorPluginStyle);
    })
    .options({
        processCssUrls: false
    })
   .sass('resources/assets/sass/app.scss', 'public/css');
